addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5

matrix:
  include:
  - os: linux
    language: python
    python: "3.6"
    compiler: gcc-5
    env: CC=gcc


sudo: false

cache: pip

install:
  - pip install -r requirements.txt

script:
  - python setup.py build_ext --inplace
