addons:
  apt:
    packages:
       - g++-5
       - gcc-5

language:
 - python
 - cpp

python:
  - "3.6"

sudo: false

cache: pip

compiler: gcc-5

install:
  - pip install -r requirements.txt

script:
  - python setup.py build_ext --inplace
